apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: graceful-gibbon-java-springboot 
  janus-idp.io/tekton: graceful-gibbon-java-springboot
  backstage.io/kubernetes-id: graceful-gibbon-java-springboot
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: graceful-gibbon-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  